import { Cairo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import OrdersContext from "@/context/OrdersContext";
import UserContext from "./context/UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cairo = Cairo({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="en">
      <body className={`antialiased ${cairo.className}`}>
        <OrdersContext>
          <UserContext>
            {children}
            <Toaster />
          </UserContext>
        </OrdersContext>
      </body>
    </html>
  );
}
